print('='*5, 'Média do aluno', '='*5)
nt1 = float(input('Digite a primeira nota do aluno: '))
nt2 = float(input('Digite a segunda nota do aluno: '))
print('A primeira nota do aluno foi: {:.1f} \na segunda nota foi: {:.1f}'.format(nt1, nt2))
print('A média do aluno foi: {:.1f}'.format(((nt1+nt2)/2)))
print('='*11, '***', '='*11)
#print(f'{(nt1+nt2)/2:.2f}')
