v = input('Digite algo: ')
print(f'O valor digitado foi: {v}')
print('Esse valor é do tipo: {}'.format(type(v)))
print('É um numéro inteiro: {}'.format(v.isnumeric()))
print('É alfabético: {}.'.format(v.isalpha()))
print('É alfanumérico: {}'.format(v.isalnum()))
print('É um número decimal: {}'.format(v.isdecimal()))
print('Está em letra(s) maiúscula(s): {}'.format(v.isupper()))
print('Está em letra(s) minúscula(s): {}'.format(v.islower()))
print(f'Contém só espaços em branco: {v.isspace()}')
print('Está capitalizada:', v.istitle())
