nome = str(input('Digite seu nome completo: ')).strip()
nome1 = nome.split()
nome2 = len(''.join(nome1))
print(f'Quantidade total de letras no seu nome com espaços: {len(nome)}.')
print(f'Seu nome em letras maiúsculas: {nome.upper()}.')
print(f'Seu nome em letras minúsculas: {nome.lower()}.')
print(f'Quantidade de letras no seu nome sem espaços: {nome2}.')
print(f'Seu primeiro nome é {nome1[0]} e tem {len(nome1[0])} letras.')
#print(len(nome) - nome.count(' '))
#print(nome.find(' ')
